version: '3'

services:
  app:
    image: node:20
    build: ./
    environment:
      DATABASE_URL: 'mysql://root:admin@db:3306/nodegql'
    depends_on:
      - db
    entrypoint: ['./entrypoint.sh']
    ports:
      - '3000:3000'

  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: nodegql
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
